### ISSUE TITLE
Why sign method 'depth' only generates positive SDF?

### ISSUE THREAD

**Issue by Colin97** [marian42/mesh_to_sdf#5] opened 2020-04-27 20:51 UTC
Thanks for your great work.

I tried to sample SDF near the surface, but it only outputs positive SDF whatever meshes (watertight or non-watertight) serve as input.

`points, sdf = sample_sdf_near_surface(mesh, number_of_points=250000, sign_method = 'depth')`

**Comment by marian42** [comment] 2020-04-27 22:04
It should generate negative values as well, can you share an example mesh where it doesn't work?

**Comment by Colin97** [comment] 2020-04-27 22:45
[mesh.zip](https://github.com/marian42/mesh_to_sdf/files/4542353/mesh.zip)

**Comment by Colin97** [comment] 2020-05-02 21:27
Is there any update?

**Comment by marian42** [comment] 2020-05-02 23:18
Sorry, I'm a bit short on time right now. I just checked your mesh. The backrest of the chair has zero volume, so it makes sense that no points are sampled inside it. For the legs of the chair, as well as the cube though, points inside of it should create negative SDF values. For comparison, I created a cube in Blender and it created negative SDFs inside it. There seems to be something weird with the topology of your mesh. I'll investigate and hopefully provide a fix.

**Comment by marian42** [comment] 2020-05-02 23:57
Ok, the issue is now fixed by disabling backface culling. I'll release an updated pip module tomorrow.

**Closed** 2020-05-02 23:56 UTC
Labels: bug

**Comment by marian42** [comment] 2020-05-03 18:53
I just uploaded a new version to pypi, you should be able to update with pip.

**Comment by Colin97** [comment] 2020-05-04 02:56
Thank you very much.
